title: Areej Mehboob - NLP Researcher
description: NLP Researcher specializing in RAG Systems, AI Agents, and Large Language Models
author: Areej Mehboob
email: mehboobareej01@gmail.com
url: https://areejmehboob.github.io

# Theme configuration
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Social links
linkedin_username: areej-mehboob-396b7a207
medium_username: mehboobareej01
github_username: areejmehboob

# SEO settings
lang: en
logo: /assets/images/profile.jpg # Add your profile image here

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Areej Mehboob"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
